### ISSUE TITLE
"Disconnected from the server" error on Shiny

### ISSUE THREAD

**Issue by eawoolard** [CRUKMI-ComputationalBiology/twoddpcr#1]
When inputting my csv file to the Shiny GUI (http://shiny.cruk.manchester.ac.uk/twoddpcr/), I receive the error "Disconnected from the server." I have tried four separate csv files on both Chrome and IE, receiving the same error. For each file, as soon as the upload is complete, I receive the error message in the bottom left corner. The csv files are around 8 kb. 
![ss 2ddpcr](https://cloud.githubusercontent.com/assets/12632870/26587484/79dc655a-4520-11e7-80bd-ae476fc8430e.png)

**Comment by idno0001** [comment]
@eawoolard I have (hopefully) fixed the problem and the Shiny GUI has been updated. Could try again to see if it's working now?

**Comment by eawoolard** [comment]
@idno0001 Thank you for the fast response- unfortunately still have the disconnection issue. Would it help if I shared the csv file I am using?

**Comment by eawoolard** [comment]
@idno0001 also, if this helps, the file I'm using is actually ~29 kb, not 8 kb. When I load similarly sized files it also crashes, but when I use smaller, random/non-ddpcr csv files it will load and not disconnect

**Comment by idno0001** [comment]
@eawoolard Thank you for the CSV file. The main issue here is that the GUI is expecting droplet **amplitude** CSV files, and it does not fail gracefully when you upload a CSV file of the 'wrong' format. I will fix this and also make it more clear what kinds of files are needed. In the meantime, the [package vignette](https://bioconductor.org/packages/devel/bioc/vignettes/twoddpcr/inst/doc/twoddpcr.html#exporting-droplet-amplitudes-from-quantasoft-to-csv-files) explains how to obtain the amplitude files from Bio-Rad's QuantaSoft.

I also noticed that your data is missing positive readings in channel 2, i.e. all values for Ch1+Ch2+ and Ch1-Ch2+ are 0, so I suspect that your droplet amplitude CSV files will only have data for one channel. The `twoddpcr` package was designed for two channel data (hence the name). I will make the GUI more robust so that it rejects one channel data with a proper error message.

If you are indeed analysing one channel data, I suggest you look at [definetherain](http://definetherain.org.uk/), which uses the same classification approach as `twoddpcr` but in one channel data only. I could add basic support for one channel data in `twoddpcr`, but this would go into the devel branch of Bioconductor and will therefore be released around 5 months from now.
